#!/bin/sh
# Platform entrypoint: installs KB Labs from local Verdaccio registry,
# scaffolds e2e workflows, starts services.
# Waits for /health (gateway process) then /ready (all upstreams including REST).
set -e

export PATH="$HOME/.local/bin:$PATH"

# ── Step 1: Install KB Labs ────────────────────────────────────────────────
echo "==> [1/3] Installing KB Labs..."
# E2E must be hermetic. The image is required to provide every bootstrap
# binary; falling back to kblabs.ru made results depend on public infrastructure.
if ! command -v kb-create > /dev/null 2>&1 || ! command -v kb-dev > /dev/null 2>&1 || ! command -v kb-devkit > /dev/null 2>&1; then
  echo "ERROR: hermetic E2E image is missing kb-create, kb-dev, or kb-devkit"
  exit 1
fi
echo "    Using binaries baked into the E2E image"
echo "    kb-create $(kb-create --version 2>&1 | head -1)"

# ── Step 2: Bootstrap project ──────────────────────────────────────────────
echo "==> [2/3] Bootstrapping project..."
mkdir -p /workspace && cd /workspace

# The V2 launcher consumes a sealed release index. The registry manifest still
# controls the E2E composition, while the index carries the platform wiring.
PLATFORM_ROOT=/workspace/kb-e2e

# ── Local observability adapters (consumer overlay) ────────────────────────────
# The sealed release index is a portable baseline on purpose: it binds only
# the transport needed to reach the installed service graph, and leaves every
# other adapter — installed, but unbound — for a consumer overlay to opt into
# (tools/kb-create/scripts/prepare-release-index.mjs, "portablePlatformAdapterConfig").
# This suite is such a consumer: workflow run logs (GET /runs/:id/logs and the
# logs WS channel) are served by platform.logs, which throws "No log storage
# backend available" without a logRingBuffer or logPersistence adapter bound.
# The ring buffer is in-process and needs no credentials or endpoints.
# Written before `kb-create apply` for the same reason as the OIDC overlay below.
mkdir -p "$PLATFORM_ROOT/.kb/overlays"
cat > "$PLATFORM_ROOT/.kb/overlays/adapters.jsonc" << 'ADAPTERS_OVERLAY'
{
  "platform": {
    "adapters": {
      "logRingBuffer": "@kb-labs/adapters-log-ringbuffer"
    }
  }
}
ADAPTERS_OVERLAY

# ── OIDC redirect-provider overlay (OAuth E2E stack only) ──────────────────────
# When OIDC_E2E_ENABLED=true (set by docker-compose.oauth-ci.yml), register a
# generic `oidc` redirect provider pointing at the in-network stub IdP, plus the
# built-in email-password door so the login page shows both. auth.providers has
# no env path by design (it is the security-sensitive extension point), so the
# only way to inject it is a config overlay — exactly how a real operator would
# wire Google/Okta/Keycloak in kb.config. The client secret stays in an env var
# (clientSecretEnv), never in the config file.
#
# This must be written BEFORE `kb-create apply`: V2's apply already starts
# every service (including gateway) as its last step, so gateway reads
# auth.providers on that very first boot. Writing the overlay afterward (as
# this script did pre-V2, when `install` and service-start were separate
# steps) leaves gateway running with whatever it saw at boot — email-password
# only — for the rest of the container's life; nothing here ever restarts it.
if [ "${OIDC_E2E_ENABLED:-false}" = "true" ]; then
  echo "    OIDC_E2E_ENABLED=true — writing oidc provider overlay"
  OIDC_ISSUER="${OIDC_CORP_ISSUER:-https://idp-stub:9443}"
  OIDC_CLIENT_ID="${OIDC_CORP_CLIENT_ID:-kb-gateway}"
  mkdir -p "$PLATFORM_ROOT/.kb/overlays"
  cat > "$PLATFORM_ROOT/.kb/overlays/oauth.jsonc" << OIDC_OVERLAY
{
  // Generated by entrypoint.sh when OIDC_E2E_ENABLED=true (OAuth E2E stack).
  "gateway": {
    "auth": {
      "providers": {
        "email-password": { "type": "email-password" },
        "corp": {
          "type": "oidc",
          "issuer": "${OIDC_ISSUER}",
          "clientId": "${OIDC_CLIENT_ID}",
          "clientSecretEnv": "OIDC_CORP_CLIENT_SECRET",
          "scopes": ["openid", "email"],
          "pkce": true
        }
      }
    }
  }
}
OIDC_OVERLAY
fi

# state-daemon binds to KB_STATE_DAEMON_HOST — override to 0.0.0.0 so it's
# reachable from the tests container via Docker bridge network. mcp-daemon
# defaults to localhost and is hit directly on :7779 by the e2e specs (not
# proxied through the gateway), so it must bind 0.0.0.0 too.
#
# Both must be exported BEFORE `kb-create apply`, same reason as the OIDC
# overlay above: apply already starts every service in the plan (including
# state-daemon and mcp-daemon) as its last step, binding to whatever host
# was in the environment at that moment. `kb-dev start` below is a no-op
# against services apply already started — it never re-binds them.
export KB_STATE_DAEMON_HOST=0.0.0.0
export KB_MCP_DAEMON_HOST=0.0.0.0

# The sealed index's binary manifest is deliberately empty (E2E never
# downloads GH release assets — see the Dockerfile), so kb-create apply
# never provisions a local .kb/v2/bin/kb-dev copy from it. --kb-dev points
# V2's service ensure/status calls at the binary already baked into the
# image instead, matching what the "Installing KB Labs" step above verified
# is present.
kb-create apply \
  --index /release-index.json \
  --request-platform-root "$PLATFORM_ROOT" \
  --project-root "$PLATFORM_ROOT" \
  --platform-channel stable \
  --service-profile default \
  --plugins "$(jq -r '[.plugins[] | select(.default == true) | .id] | join(",")' /e2e-registry-manifest.json)" \
  --adapters "$(jq -r '[.adapters[].id] | join(",")' /release-index.json)" \
  --registry http://verdaccio:4873 \
  --kb-dev /usr/local/bin/kb-dev
cd "$PLATFORM_ROOT"

# Bootstrap admin for E2E — gateway creates this user on first start.
# Tests obtain machine-client credentials by logging in as admin and calling
# POST /auth/register (no static tokens needed).
#
# Use ${VAR:-default} so docker-compose overrides take precedence.
# docker-compose.auth-ci.yml injects auth-specific credentials; without this
# guard the assignments below would overwrite those injected values and the
# auth E2E tests would always get 401 (wrong bootstrap email / tenant).
GATEWAY_BOOTSTRAP_ADMIN_EMAIL="${GATEWAY_BOOTSTRAP_ADMIN_EMAIL:-admin@e2e.test}"
GATEWAY_BOOTSTRAP_ADMIN_PASSWORD="${GATEWAY_BOOTSTRAP_ADMIN_PASSWORD:-E2eBootstrapPass1!}"
GATEWAY_BOOTSTRAP_TENANT_ID="${GATEWAY_BOOTSTRAP_TENANT_ID:-kblabs-cloud}"
export GATEWAY_BOOTSTRAP_ADMIN_EMAIL GATEWAY_BOOTSTRAP_ADMIN_PASSWORD GATEWAY_BOOTSTRAP_TENANT_ID

# Scaffold test workflows used by E2E suite
mkdir -p .kb/workflows

cat > .kb/workflows/e2e-hello.yml << 'EOF'
name: e2e-hello
version: 1.0.0
description: E2E smoke workflow — runs echo and exits cleanly
on:
  manual: true
jobs:
  greet:
    runsOn: local
    steps:
      - name: Say hello
        uses: builtin:shell
        with:
          command: echo "hello from e2e"
EOF

cat > .kb/workflows/e2e-fail.yml << 'EOF'
name: e2e-fail
version: 1.0.0
description: E2E failure workflow — intentionally exits non-zero
on:
  manual: true
jobs:
  fail:
    runsOn: local
    steps:
      - name: Fail intentionally
        uses: builtin:shell
        with:
          command: exit 1
EOF

cat > .kb/workflows/e2e-slow.yml << 'EOF'
name: e2e-slow
version: 1.0.0
description: E2E slow workflow — sleeps 10s so reconnect tests can observe in-progress runs
on:
  manual: true
jobs:
  wait:
    runsOn: local
    steps:
      - name: Sleep
        uses: builtin:shell
        with:
          command: sleep 10
EOF

cat > .kb/workflows/e2e-approval.yml << 'EOF'
name: e2e-approval
version: 1.0.0
description: E2E approval workflow — pauses for human approval then continues
on:
  manual: true
jobs:
  gate:
    runsOn: local
    steps:
      - name: Before gate
        uses: builtin:shell
        with:
          command: echo "before approval"
      - name: Human gate
        uses: builtin:approval
        with:
          title: E2E approval check
          instructions: Approve to continue, reject to stop
      - name: After gate
        uses: builtin:shell
        with:
          command: echo "after approval"
EOF

# ── Step 3: Start backend services ────────────────────────────────────────
# Start infra first (state-daemon), then backend group.
# kb-dev start accepts one service/group name — not multiple.
# Redis is optional (in-memory fallback); qdrant skipped (mind/RAG only, not needed for e2e).
echo "==> [3/3] Starting services..."
# KB_STATE_DAEMON_HOST / KB_MCP_DAEMON_HOST are exported above, before
# `kb-create apply`, so both daemons already bound 0.0.0.0 on their first
# (and only) boot. These calls just cover the case a service didn't come up
# clean out of apply.
kb-dev start state-daemon &
sleep 3
kb-dev start backend &

echo "==> Waiting for gateway process to start (/health)..."
ATTEMPTS=0
until curl -sf http://localhost:4000/health > /dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if [ "$ATTEMPTS" -ge 300 ]; then
    echo "ERROR: Gateway did not start after 600s"
    kb-dev status || true
    exit 1
  fi
  sleep 2
done
echo "    Gateway process up after ${ATTEMPTS}x2s"

# Wait for all upstreams to be wired (/ready returns 200 only when REST API,
# workflow daemon, marketplace etc. are all responding).
# Docker Compose healthcheck also polls /ready — we must be ready before tail.
echo "==> Waiting for all services to be ready (/ready)..."
ATTEMPTS=0
until curl -sf http://localhost:4000/ready > /dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if [ "$ATTEMPTS" -ge 60 ]; then
    echo "ERROR: Platform /ready did not pass after 120s — upstreams still down"
    kb-dev status || true
    curl -s http://localhost:4000/ready || true
    exit 1
  fi
  sleep 2
done

echo "==> Platform fully ready after ${ATTEMPTS}x2s"

echo "==> Waiting for marketplace-registry (/health)..."
ATTEMPTS=0
until curl -sf http://localhost:5071/health > /dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if [ "$ATTEMPTS" -ge 30 ]; then
    echo "WARN: marketplace-registry did not respond after 60s — continuing anyway"
    break
  fi
  sleep 2
done
if curl -sf http://localhost:5071/health > /dev/null 2>&1; then
  echo "    marketplace-registry ready after ${ATTEMPTS}x2s"
fi

kb-dev status

# Keep container alive while tests run
exec tail -f /dev/null
